algolia/react-element-to-jsx-string

index-test.js, index.js
When decorating components the resulting tagName was `[object Object]`
=> fix(tagName): fixed an edge-case with decorated component name

index.js, npm-shrinkwrap.json, package.json
because not all VMs have implemented Array.prototype.fill yet
fix https://github.com/algolia/react-element-to-jsx-string/issues/9
=> use fill from lodash

index-test.js, tests/StatelessAnonComponent.js, tests/StatelessComponent.js
When exporting a Stateless Component, there are 2 cases.
Case: 1
export default function(props) {....}
Case:2
export default function FlexItem(props) {....}
Generally, we ensure that the Component is named. However, even anonymous functions are valid React stateless components. The test case for case:1 is failing. This only occurs when the components are exported. Otherwise, it works perfectly fine.
=> Added test case for Stringifying imported stateless components

index-test.js, index.js
It is not meaningful child and should be filtered.
=> Fix <div>{''}</div>

index-test.js, index.js
Closes https://github.com/algolia/react-element-to-jsx-string/issues/15
This adds the ability to pass a custom function to format the way components are displayed in the final string.
I've had to pass around the `options` object on all the functions used for recursion. This in my opinion is not very clear, I think it may be better to move the small function under `toJSXString` so that the `options` variable is in scope and can be accessed whenever we recurse again from those functions.
If you agree that's clearer and prefer that approach instead of this current one, let me know and I can modify the PR.
=> Add displayName option for custom formatting

README.md, index-test.js, index.js
according to https://facebook.github.io/react/docs/jsx-in-depth.html#boolean-attributes it is ok to omit the value of boolean attributes if the value is true. Attributes with value false are unnecessary.
This PR allows (via options: {omitBools: true}) that
```
<Button primary={true}>A Button</Button>
```
becomes
```
<Button primary>A Button</Button>
```
I think this is a good idea in general, but I thought I'll create a option for this, as this is unexpected behavior for existing consumers. What do you think? Should the short syntax be the default?
=> allow omitting boolean attributes

index-test.js, index.js
This fixes an issue that occurs when the `showDefaultProps` option is
`false` but a prop differs from its default value. Previously the prop
would not be rendered at all. Now it will only be omitted if it matches
its default value.
=> Fix for issue #28

index-test.js, index.js
Changed the order because `ReactElement.type.name` returns something that doesn't represent the name of the component.
For example if the component was called `Button` it would return a random letter instead like 'L' or 't'.
=> change order of where to get the name of a component from

AnonymousStatelessComponent.js, README.md, index-test.js, index.js
For us weird folk that don't use shorthand syntax (I know I know) this adds a configurable option to output boolean values like:
```jsx
<Component prop={true} prop={false} />
```
Default is set to `true` for backwards compatibility ... and also because I imagine the majority use the shorthand syntax. 
_Also there were a couple of eslint errors, not sure if they were there before... I don't think I have any global eslint config madness sneaking in there_
=> Added configurable option to explicitly output boolean prop values. 

README.md, index-test.js, index.js
We have situations where we need to add a key property to the input of `reactElementToJsxString` but not to have it printed in the output. This adds a `showKey` option to not print the key prop.
When the import syntax like below is used
```
import {fill} from 'lodash';
``` 
it still requires the whole library, but changing it to 
```
import fill from 'lodash/fill';
```
It will only require that util.
Our build size before this change was `2,428,686 bytes` and afterwards it dropped to `1,898,514 bytes`
=> `filterProps` Option

README.md, index-test.js, index.js
Would you be open to adding a `maxInlineAttributes` option (or something similarly named)?
I'm using your library to render demonstration documentation where I show a react component running on a page and the react component source on the same page. For some of my simpler components, I'd like to have all of their props render on the same line as the tag:
```jsx
<Header level={2} kind="heading1">
Content
</Header>
```
See the tests I've added for more comprehensive examples of the behavior. All existing tests pass so this should not break any existing behavior.
=> Add maxInlineAttributes option

index-test.js, index.js
Looks like this case was not managed and that we encountered it 😉
=> Fix edge case when props contains double quote

index-test.js
Occurs in nested JSX that contains single quotes
Issue #80
=> Add failing test for unnecessary string escaping

index-test.js, index.js
The logic for filtering out defaultProps wasn't taking into account falsey values that are actually defined as default props.
=> always filter out props that have a value of undefined

package.json
This repository appears to have a setting that all PRs must be up-to-date with the base branch before merging. For example, #117:
Therefore it is recommended to enable the setting `rebaseStalePrs` in Renovate so that it knows to keep branches up-to-date itself and save you the task of doing it. It means Renovate will rebase any of its PRs off master any time it runs and finds that the master branch has changed.
=> Configure Renovate to rebase stale PRs

package.json
Like we discuss in https://github.com/algolia/react-element-to-jsx-string/pull/113#issuecomment-317688872
See the doc: https://renovateapp.com/docs/configuration-reference/package#automerge
=> chore(deps): Automerge renovate PR for minor dependencies upgrade

package.json
Ran tests with react 15 and react 16 and all passed.
This is necessary to use with react native >= 0.43 (latest is 0.47-rc).
@Spy-Seth @vvo
=> Allow react 16 as a peer dependency

src/formatter/formatPropValue.js, src/formatter/formatPropValue.spec.js, src/index.spec.js
Closes #134
BREAKING CHANGE: Symbol description are now correctly quoted. This change the output if you use Symbol in your code
=> fix(formatting): symbol description are now quoted

src/formatter/formatProp.js, src/formatter/formatTreeNode.js, src/index.spec.js
Closes #135
BREAKING CHANGE: Trailling are now preserved. In some rare case, `react-element-to-jsx-string` failed to respect the JSX specs for the trailing space. Event is the space were in the final output. There were silentrly ignored by JSX parser. This commit fix this bug by protecting the trailing space in the output.
If we take the JSX:
```jsx
<div>
foo <strong>bar</strong> baz
</div>
```
Before it was converted to (the trailing space are replace by `*` for the readability):
```jsx
<div>
foo*
<strong>
bar
</strong>
*baz
</div>
```
Now there are preserved:
```jsx
<div>
foo{' '}
<strong>
bar
</strong>
{' '}baz
</div>
```
=> fix(formatting): trailling space

package.json
Yarn is not in dependencies and no reason for this. Script fails when run with no global yarn. With npm works just fine.
=> Fix yarn -> npm

src/index.js, src/parser/parseReactElement.js
Explicit import of React's types to avoid star import that leads to warning about access to PropTypes.
=> Fix warning about access to PropTypes using React 15.5+ (fixes #213)

package.json, src/formatter/formatComplexDataStructure.js, yarn.lock
Remove `collapse-white-space` from deps since module is just a single simple regexp:
https://github.com/wooorm/collapse-white-space/blob/master/index.js#L7
=> chore(deps): Remove `collapse-white-space` from deps

package.json, src/formatter/formatComplexDataStructure.js, src/formatter/formatComplexDataStructure.spec.js, src/formatter/sortObject.js, src/formatter/sortObject.spec.js, yarn.lock
`sortobject` breaks output of Date and RegExp values, since makes an object copy of those values instead returning as is. Therefore, `formatComplexDataStructure` for following object
```js
{
date: new Date('2017-11-13T00:00:00.000Z'),
regexp: /test/g
}
```
outputs
```js
{
date: {},
regexp: {}
}
```
We can fix `sortobject` by sending a PR. But its [implementation is too verbose](https://github.com/bevry/sortobject/blob/master/source/index.js) for such simple task. So I decided to add an own implementation of `sortObject` instead of patching `sortobject`. This also helps keep things simpler and allows adjust behaviour if needed.
=> fix(formatting): Date/RegExp values output by formatComplexDataStructure

.travis.yml, package.json, tests/smoke/.gitignore, tests/smoke/prepare.js, tests/smoke/run.js, tests/smoke/smoke.js, yarn.lock
Do not be scare by the number of line of code, it's mostly some `yarn.lock` file
This PR introduce a new tests suite called `smoke`. It tests that the library seems to works with multiple version React (v0.14, v15 and v16): it only validate some basic usage.
It also rework the `travis.yml` file to test our code with multiple node versions (the last v7, the last LTS/v8, and the last v9)
=> qa(test): test the library agains more react and node versions

rollup.config.js
This adds IE 11 support as well as support for older versions of Uglify.
It does so by transpiling `stringify-object` with babel.
Closes #211, #285
=> fix(browser): Add IE 11 support

src/formatter/sortObject.js
Now supports:
```jsx
<Component
props={{
subcomponent: <AnotherComponent />,
}}
/>
```
Fixes #307
=> fix(formatting) Fix JSX element in prop object recursive loop

package.json, rollup.config.js, src/formatter/formatComplexDataStructure.js, yarn.lock
Fix for #387 to replace stringify-object and make the output compatible with ES5.
=> Fix output for es5

.npmignore
Looking for simple issues to help with for Hacktoberfest, I stumbled upon this repo :slightly_smiling_face:
This PR fixes issue #414
=> chore: ignore test files when publishing

README.md, src/formatter/createPropFilter.js, src/formatter/createPropFilter.spec.js, src/formatter/formatReactElementNode.js, src/formatter/formatReactElementNode.spec.js, src/index.spec.js
filterProps can now be passed as either an array of strings, or a function that will be called with the props value and key and return false to filter out that prop.
Closes #286
=> feat: allow filterProps to be a function

src/formatter/formatTreeNode.js, src/index.spec.js
`/^(\S*)(\s*)$/` will not match if there are multiple words before the trailing space due to it trying to match non-space characters before the trailing space.
Without the fix, the following test will fail
=> Handle multiple words before trailing space, and after leading space

src/formatter/formatPropValue.js, src/formatter/formatPropValue.spec.js
calling toISOString() on an invalid Date object will throw a Range Error
=> fix: handle invalid Date objects (#605)

src/formatter/sortObject.js, src/formatter/sortObject.spec.js
It fixes https://github.com/algolia/react-element-to-jsx-string/issues/681
The bug was introduced in https://github.com/algolia/react-element-to-jsx-string/pull/619.
It's not a first time since we encounter this issue, see https://github.com/algolia/react-element-to-jsx-string/issues/307 and especially https://github.com/algolia/react-element-to-jsx-string/pull/312#issuecomment-427134793. 
I faced it in storybook and managed to reproduce it using this story:
```typescript
import { Meta, Story } from "@storybook/react";
import { Buttons, ButtonsProps } from "./Buttons";
export default {
title: "Components/Buttons",
component: Buttons,
} as Meta<ButtonsProps>;
export const Default: Story<ButtonsProps> = ({}: ButtonsProps) => (
<div
buttons={[
{
foo: "bar",
jsx: <div key="1">Button in …
```
=> Fix recursion with react elements
